### ISSUE TITLE
Ummmmm

### ISSUE THREAD

**Issue by MinecraftPublisher** [anasouardini/portal#1]
Have you by any chance heard of z?
https://github.com/rupa/z

or zoxide
https://github.com/ajeetdsouza/zoxide

**Comment by anasouardini** [comment]
I've only tried Zoxide before and I'm sure both of the the plugins you've listed are great, thanks for suggestion. However, I tend to lean towards simplicity.

I don't think fully-fledged alternatives are bad, but it's just not what I need.
